### ISSUE TITLE
How to install on heroku?

### ISSUE THREAD

**Issue by ptgamr** [leplatrem/cliquet-pusher#14]
I can run `heroku run --app <app> pip install kinto-pusher`  successfully, but failed to push the changes to heroku after enable pusher in the configuration file.

**Comment by leplatrem** [comment]
Do you mind if we move the question to kinto-heroku instead ? https://github.com/Kinto/kinto-heroku

Once we figure out the whole process properly, I would be in favor of adding a paragraph in the README of this repo

**Comment by Natim** [comment]
You can update the config in the kinto-heroku repository to activate kinto-pusher

**Comment by Natim** [comment]
Refs https://github.com/Kinto/kinto-heroku/issues/20
